POST http://localhost:8080/events
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvcmRhbkBleGFtcGxlLmNvbSIsImV4cCI6MTc2NzE5Mjc3NiwidXNlcklkIjoyfQ.3ipPwZf8IJ_6KD4sWyg9g-atLk6Kj_HjSCD6vRL8Wmo

{
    "Name": "Test Event 1 by Jordan",
    "Description": "This is a test event created via API. 1",
    "Location": "Test Location 1",
    "DateTime": "2024-07-01T10:00:00Z"
}
