PUT http://localhost:8080/events/3
Content-Type: application/json

{
    "Name": "updated 3rd event",
    "Description": "updated description for 3rd event",
    "Location": "updated location for 3rd event",
    "DateTime": "2024-07-02T15:00:00Z"
}